import { Main } from "next/document";
import Head from "next/head";
import Content from "../components/Content";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className='bg-gradient-to-b from-SoftViolet to-SoftBlue w-screen min-h-screen flex flex-col justify-center items-center'>
      <Head>
        <title>FAQ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Content />
      <Footer />
    </div>
  );
}
