import Head from "next/head";
import Image from "next/image";
import ImageMobile from "../public/illustration-woman-online-mobile.svg";
import Data from "../data.json";
import Accordion from "../components/Accordion";

export default function Home() {
  return (
    <div className='bg-gradient-to-b from-SoftViolet to-SoftBlue w-screen min-h-screen flex flex-col justify-center items-center'>
      <Head>
        <title>FAQ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='m-0 bg-white w-[330px] min-h-[535px] flex flex-col items-center rounded-3xl'>
        <Image
          src={ImageMobile}
          alt='Women with computer'
          width={230}
          height={230}
          className='relative top-[-100px]'
        />
        <h1 className='text-darkBlue font-bold text-center text-4xl relative top-[-3.75rem]'>
          FAQ
        </h1>
        <div className='flex flex-col gap-6 relative top-[-2.5rem] w-[80%]'>
          {Data.map((item) => (
            <Accordion
              key={item.id}
              title={item.title}
              content={item.content}
            />
          ))}
          
        </div>
      </main>

      <footer className='mt-5 text-center'>
        Challenge by{" "}
        <a
          href='https://www.frontendmentor.io?ref=challenge'
          target='_blank'
          className='hover:text-SoftRed'>
          Frontend Mentor
        </a>
        . <br />
        Coded by{" "}
        <a
          href='https://portfolio-yixuan-wang.vercel.app/'
          target='_blank'
          className='hover:text-SoftRed'>
          Yixuan Wang
        </a>
        .
      </footer>
    </div>
  );
}
